# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Basys3_XDC/MY_Basys-3-Master.xdc

# Block Designs: bd/design_MicoBlaze_Led/design_MicoBlaze_Led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led || ORIG_REF_NAME==design_MicoBlaze_Led} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_microblaze_0_0/design_MicoBlaze_Led_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_microblaze_0_0 || ORIG_REF_NAME==design_MicoBlaze_Led_microblaze_0_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_axi_uartlite_0_0/design_MicoBlaze_Led_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_axi_uartlite_0_0 || ORIG_REF_NAME==design_MicoBlaze_Led_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_axi_gpio_0_0/design_MicoBlaze_Led_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_axi_gpio_0_0 || ORIG_REF_NAME==design_MicoBlaze_Led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_dlmb_v10_0/design_MicoBlaze_Led_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_dlmb_v10_0 || ORIG_REF_NAME==design_MicoBlaze_Led_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_ilmb_v10_0/design_MicoBlaze_Led_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_ilmb_v10_0 || ORIG_REF_NAME==design_MicoBlaze_Led_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_dlmb_bram_if_cntlr_0/design_MicoBlaze_Led_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MicoBlaze_Led_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_ilmb_bram_if_cntlr_0/design_MicoBlaze_Led_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_MicoBlaze_Led_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_lmb_bram_0/design_MicoBlaze_Led_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_lmb_bram_0 || ORIG_REF_NAME==design_MicoBlaze_Led_lmb_bram_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_mdm_1_0/design_MicoBlaze_Led_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_mdm_1_0 || ORIG_REF_NAME==design_MicoBlaze_Led_mdm_1_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_clk_wiz_1_0/design_MicoBlaze_Led_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_clk_wiz_1_0 || ORIG_REF_NAME==design_MicoBlaze_Led_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_rst_clk_wiz_1_100M_0/design_MicoBlaze_Led_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_MicoBlaze_Led_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_xbar_0/design_MicoBlaze_Led_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_xbar_0 || ORIG_REF_NAME==design_MicoBlaze_Led_xbar_0} -quiet] -quiet

# IP: bd/design_MicoBlaze_Led/ip/design_MicoBlaze_Led_microblaze_0_axi_periph_0/design_MicoBlaze_Led_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MicoBlaze_Led_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_MicoBlaze_Led_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/design_MicoBlaze_Led/design_MicoBlaze_Led_ooc.xdc
